# Comparação entre os modelos utilizando a base de dados MNIST

MNIST é uma base de dados de imagens de dígitos manuscritos que é amplamente utilizada em testes e benchmarks de modelos de aprendizado de máquina. A base de dados MNIST foi criada pelo National Institute of Standards and Technology (NIST) dos EUA e contém 60.000 imagens de treinamento e 10.000 imagens de teste de dígitos manuscritos de 0 a 9. As imagens são em preto e branco e têm 28x28 pixels cada.

MNIST é uma base de dados popular entre os pesquisadores e desenvolvedores de modelos de aprendizado de máquina, pois é de fácil acesso e contém um conjunto de dados bem definido e de fácil utilização. É comumente usada como um benchmark para avaliar o desempenho de diferentes modelos de aprendizado de máquina em tarefas de classificação de imagens.

In [ ]:
import joblib

from sklearn.metrics import confusion_matrix,ConfusionMatrixDisplay
from sklearn.metrics import classification_report
import numpy as np

from io import BytesIO
import requests
import time

In [ ]:
from keras.datasets import mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_test = (X_test.astype(np.float32))
X_test = X_test.reshape(10000, 784)


## Algoritmo KNN

In [ ]:
mLink = 'https://github.com/diegonogare/MachineLearning/blob/main/modelo_knn_mnist.pkl?raw=true'
mfile = BytesIO(requests.get(mLink).content)
modelo_knn = joblib.load(mfile)

In [ ]:
print(modelo_knn)

inicio = time.time()
predicao_knn = modelo_knn.predict(X_test)
termino = time.time()
print("[%s segundos para fazer o scoring do modelo]" % (termino - inicio))

predicao_knn = predicao_knn.astype(np.int64)
matriz_confusao = confusion_matrix(y_test, predicao_knn)
print(matriz_confusao) 
print('-'*40)
print(classification_report(y_test, predicao_knn))

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=KNeighborsClassifier(),
             param_grid=[{'metric': ['euclidean'], 'n_neighbors': [3, 5, 7, 9],
                          'weights': ['uniform', 'distance']}],
             verbose=3)


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


[38.627347469329834 segundos para fazer o scoring do modelo]
[[ 980    0    0    0    0    0    0    0    0    0]
 [   0 1135    0    0    0    0    0    0    0    0]
 [   0    0 1032    0    0    0    0    0    0    0]
 [   0    0    0 1010    0    0    0    0    0    0]
 [   0    0    0    0  982    0    0    0    0    0]
 [   0    0    0    0    0  892    0    0    0    0]
 [   0    0    0    0    0    0  958    0    0    0]
 [   0    0    0    0    0    0    0 1028    0    0]
 [   0    0    0    0    0    0    0    0  974    0]
 [   0    0    0    0    0    0    0    0    0 1009]]
----------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       980
           1       1.00      1.00      1.00      1135
           2       1.00      1.00      1.00      1032
           3       1.00      1.00      1.00      1010
           4       1.00      1.00      1.00       982
           5       1.00      1.00      1.0

## Algoritmo Decision Tree

In [ ]:
mLink = 'https://github.com/diegonogare/MachineLearning/blob/main/modelo_dt_mnist.pkl?raw=true'
mfile = BytesIO(requests.get(mLink).content)
modelo_dt = joblib.load(mfile)

In [ ]:
print(modelo_dt)

inicio = time.time()
predicao_dt = modelo_dt.predict(X_test)
termino = time.time()
print("[%s segundos para fazer o scoring do modelo]" % (termino - inicio))

predicao_dt = predicao_dt.astype(np.int64)
matriz_confusao = confusion_matrix(y_test, predicao_dt)
print(matriz_confusao) 
print('-'*40)
print(classification_report(y_test, predicao_dt))

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=DecisionTreeClassifier(),
             param_grid=[{'criterion': ['gini', 'entropy'],
                          'max_depth': [10, 50, 80]}],
             verbose=3)
[0.01206064224243164 segundos para fazer o scoring do modelo]
[[ 980    0    0    0    0    0    0    0    0    0]
 [   0 1135    0    0    0    0    0    0    0    0]
 [   0    0 1032    0    0    0    0    0    0    0]
 [   0    0    0 1010    0    0    0    0    0    0]
 [   0    0    0    0  982    0    0    0    0    0]
 [   0    0    0    0    0  892    0    0    0    0]
 [   0    0    0    0    0    0  958    0    0    0]
 [   0    0    0    0    0    0    0 1028    0    0]
 [   0    0    0    0    0    0    0    0  974    0]
 [   0    0    0    0    0    0    0    0    0 1009]]
----------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00   

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


## Algoritmo Multi-Layer Perceptron

In [ ]:
mLink = 'https://github.com/diegonogare/MachineLearning/blob/main/modelo_mlp_mnist.pkl?raw=true'
mfile = BytesIO(requests.get(mLink).content)
modelo_mlp = joblib.load(mfile)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator MLPClassifier from version 1.1.3 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator LabelBinarizer from version 1.1.3 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator GridSearchCV from version 1.1.3 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. 

In [ ]:
print(modelo_mlp)

inicio = time.time()
predicao_mlp = modelo_mlp.predict(X_test)
termino = time.time()
print("[%s segundos para fazer o scoring do modelo]" % (termino - inicio))

predicao_mlp = predicao_mlp.astype(np.int64)
matriz_confusao = confusion_matrix(y_test, predicao_mlp)
print(matriz_confusao) 
print('-'*40)
print(classification_report(y_test, predicao_mlp))

GridSearchCV(cv=StratifiedKFold(n_splits=10, random_state=42, shuffle=True),
             estimator=MLPClassifier(),
             param_grid=[{'activation': ['tanh', 'relu'],
                          'hidden_layer_sizes': [100, (10, 10), (15, 15),
                                                 (20, 20)],
                          'solver': ['sgd', 'adam']}],
             verbose=3)


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  "X does not have valid feature names, but"


[0.10040473937988281 segundos para fazer o scoring do modelo]
[[ 979    0    0    0    0    0    0    1    0    0]
 [   0 1134    0    0    0    0    0    1    0    0]
 [   0    3 1024    1    1    0    0    1    2    0]
 [   0    0    1 1000    0    1    0    2    0    6]
 [   0    0    0    0  975    0    0    1    0    6]
 [   0    0    0    1    0  888    0    0    3    0]
 [   0    0    0    0    0    1  955    0    2    0]
 [   1    1    1    0    0    0    0 1024    0    1]
 [   0    0    5    2    0    1    1    2  959    4]
 [   0    0    0    4    0    0    0    0    0 1005]]
----------------------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       980
           1       1.00      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       1.00      0.99      1.00       982
           5       1.00      1.00      1.

## Referências

LeCun, Yann, et al. "MNIST handwritten digit database." AT&T Labs [Online]. Available: http://yann.lecun.com/exdb/mnist/. [Acessado em 05-Dezembro-2022].

Géron, Aurélien. Hands-on machine learning with Scikit-Learn, Keras, and TensorFlow: concepts, tools, and techniques to build intelligent systems. O'Reilly Media, 2019.